### ISSUE TITLE
지출결의서((개인경비

### ISSUE THREAD

**Issue by transformorr** [hotorch/acc_contents_selenium#1]
![image](https://user-images.githubusercontent.com/59192848/131424790-c5329de0-06c3-4e38-a534-4517103aa087.png)

아래 코드에서 해당 이미지처럼 지출결의서 항목을 클릭하지 못하는 에러 발생

`finance_templete = driver.find_element_by_xpath('//*[@id="26"]/a').click()`

solve) click() 함수를 send_keys(Keys.ENTER) 로 변경

`from selenium.webdriver.common.keys import Keys`
`finance_templete = driver.find_element_by_xpath('//*[@id="26"]/a').send_keys(Keys.ENTER)`

**Comment by hotorch** [comment]
Thank you for making it work more generalized.
