### ISSUE TITLE
selenium 버전 이슈가 있습니다.

### ISSUE THREAD

**Issue by sungreong** [hotorch/acc_contents_selenium#2]
안녕하세요. 
애자일소다 선임연구원 이성령입니다

사용을 하다가 selenium 버전 이슈가 있어서 이슈 날립니다.

최신 버전인 4.0.0으로 했을 때 작동하지 않다가 3.141.0으로 설치했을 때 작동하였습니다.

좋은거 만들어 주셔서 감사합니다 :)

**Comment by hotorch** [comment]
이런 누추한 곳에 와주셔서 부끄럽네요. 해당 부분은 README에 반영을 하였습니다.

좋다고 해주시니 감사하네요! 앞으로 다른 이슈 있으면 날려주시면 감사하겠습니다.

좋은 하루 되십시오!
