### ISSUE TITLE
'WebDriver' object has no attribute 'switch_to_window'

### ISSUE THREAD

**Issue by statbsh** [hotorch/acc_contents_selenium#3]
로그인을 실시합니다
---팝업창 유의---
아래 하단 결재양식 > 톱니바퀴 > 휴가신청서와 지출결의서(개인경비)를 추가해주세요.
Traceback (most recent call last):
  File "acc_selenium.py", line 53, in <module>
    driver.switch_to_window(driver.window_handles[0]) # main page
AttributeError: 'WebDriver' object has no attribute 'switch_to_window'

로그인 까지 성공 후 다음의 에러가 뜹니다.

**Comment by hotorch** [comment]
pip install selenium==3.141.0

로 버전 바꾸어서 하시길 바랍니다. 해당 함수가 바뀌어서 생긴 에러 입니다.
